---
# Source: generic-helm-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret1
  namespace: 2-assignment
type: Opaque
data:
  POSTGRES_USER: dmlrYXM=          # 'vikas' in base64
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # 'admin123' in base64
  POSTGRES_DB: bXlkYg==             # 'mydb' in base64
---
# Source: generic-helm-chart/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config1
  namespace: 2-assignment
data:
  DB_HOST: postgres1
  DB_PORT: "5432"
---
# Source: generic-helm-chart/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service1
  namespace: 2-assignment
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Source: generic-helm-chart/templates/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres1
  namespace: 2-assignment
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
---
# Source: generic-helm-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: 2-assignment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "vikasgirigoswami/last:latest"
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config1
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config1
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_DB
---
# Source: generic-helm-chart/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbstatefulset1
  namespace: 2-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret1
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage1
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage1
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
