apiVersion: v1
kind: Service
metadata:
  name: backend-service1
  namespace: 2-assignment
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
